import { collection, addDoc, serverTimestamp, query, where, orderBy, onSnapshot, updateDoc, doc, deleteDoc, writeBatch, getDocs, or, setDoc } from 'firebase/firestore';
import { db, messaging } from '../firebase';
import { getToken } from 'firebase/messaging';

export type NotificationType = 

  | 'profile_update' 
  | 'schedule_change' 
  | 'doubt_reply' 
  | 'material_upload' 
  | 'doubt_raised' 
  | 'fee_payment' 
  | 'fee_confirmed' 
  | 'new_student'
  | 'chat_message'
  | 'group_chat_message';

export interface Notification {
  id?: string;
  recipientId?: string;
  targetRole?: 'teacher' | 'student' | 'admin' | 'ALL';
  senderId: string;
  senderName: string;
  title: string;
  message: string;
  type: NotificationType;
  read: boolean;
  createdAt: any;
  timestamp?: any;
  relatedId?: string;
  targetDept?: string;
  targetSem?: string;
  isAnonymous?: boolean;
}

export const sendNotification = async (notification: Omit<Notification, 'id' | 'createdAt' | 'read'>) => {
  await addDoc(collection(db, 'notifications'), {
    ...notification,
    read: false,
    createdAt: serverTimestamp(),
    timestamp: serverTimestamp(),
  });

  // Call our own backend API to trigger the push notification!
  // This replaces the need for paid Firebase Cloud Functions.
  try {
    await fetch('/api/send-push', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: notification.title,
        body: notification.message,
        recipientId: notification.recipientId,
        targetRole: notification.targetRole,
        type: notification.type,
        chatId: notification.relatedId,
        senderId: notification.senderId,
        targetDept: notification.targetDept,
        targetSem: notification.targetSem,
      })
    });
  } catch (error) {
    console.error('Failed to trigger background push notification:', error);
  }
};

export const subscribeToNotifications = (userId: string, targetRole: string, callback: (notifications: Notification[]) => void, userDept?: string, userSem?: string) => {
  if ('Notification' in window && Notification.permission === 'default') {
    Notification.requestPermission();
  }

  const q = query(
    collection(db, 'notifications'),
    orderBy('createdAt', 'desc')
  );

  let isInitialLoad = true;

  return onSnapshot(q, (snapshot) => {
    let notifications = snapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    } as Notification));
    
    // Client-side filtering to avoid complex composite index error
    notifications = notifications.filter(n => {
      // Don't show notifications generated by the current user
      if (n.senderId === userId) return false;
      
      // Always show direct messages to the user
      if (n.recipientId === userId) return true;
      
      // If the notification targets a specific recipient and it's not the current user, hide it.
      if (n.recipientId && n.recipientId !== userId) return false;
      
      // Filter role base
      if (n.targetRole === targetRole || n.targetRole === 'ALL') {
        // If there are department constraints on the notification and the user has a department to check against
        if (n.targetDept && userDept) {
          if (n.targetDept.toLowerCase() !== userDept.toLowerCase() && n.targetDept !== 'ALL') return false;
        }
        if (n.targetSem && userSem) {
          if (String(n.targetSem) !== String(userSem) && n.targetSem !== 'ALL') return false;
        }
        return true;
      }
      
      return false;
    });
    
    if (!isInitialLoad) {
       snapshot.docChanges().forEach(change => {
          if (change.type === 'added') {
             const newNotif = { id: change.doc.id, ...change.doc.data() } as Notification;
             const isForMe = notifications.some(n => n.id === newNotif.id);
             if (isForMe && !newNotif.read) {
                // Play Sound
                try {
                   const AudioContext = null; // const original = window.AudioContext || (window as any).webkitAudioContext;
                   if (AudioContext) {
                     const audioCtx = new AudioContext();
                     const oscillator = audioCtx.createOscillator();
                     const gainNode = audioCtx.createGain();

                     oscillator.type = 'sine';
                     oscillator.frequency.setValueAtTime(800, audioCtx.currentTime);
                     oscillator.frequency.exponentialRampToValueAtTime(1200, audioCtx.currentTime + 0.05);

                     gainNode.gain.setValueAtTime(0, audioCtx.currentTime);
                     gainNode.gain.linearRampToValueAtTime(0.5, audioCtx.currentTime + 0.02);
                     gainNode.gain.linearRampToValueAtTime(0, audioCtx.currentTime + 0.15);

                     oscillator.connect(gainNode);
                     gainNode.connect(audioCtx.destination);

                     oscillator.start(audioCtx.currentTime);
                     oscillator.stop(audioCtx.currentTime + 0.15);
                   }
                } catch(e) {
                   console.log('Audio could not be played', e);
                }

                // Dispatch a custom event to trigger custom UI in-app dynamic Toast popups!
                // In-app visual popup dispatch removed per user request

                // Robust browser-native notification popup fallback!
                if ('Notification' in window && Notification.permission === 'granted') {
                   // Only show if the app is hidden or user specifically wants outer notification
                   if (document.visibilityState === 'hidden' || true) {
                     try {
                        if ('serviceWorker' in navigator) {
                           navigator.serviceWorker.ready.then(registration => {
                             registration.showNotification(newNotif.title, {
                                body: newNotif.message,
                                icon: window.location.origin + '/gold_tuitionhub_logo_1779680854835.png',
                                badge: window.location.origin + '/notification-badge.svg',
                                vibrate: [100, 50, 100],
                                tag: newNotif.id
                             } as any).catch(e => {
                                console.warn('SW notification failed:', e);
                                // Fallback for desktop Safari if SW doesn't support showNotification
                                new Notification(newNotif.title, { body: newNotif.message, icon: window.location.origin + '/gold_tuitionhub_logo_1779680854835.png', badge: window.location.origin + '/notification-badge.svg' });
                             });
                           });
                        } else {
                           new Notification(newNotif.title, { body: newNotif.message, icon: window.location.origin + '/gold_tuitionhub_logo_1779680854835.png' });
                        }
                     } catch (e) {
                       console.warn('Native notification instantiation failed: ', e);
                     }
                   }
                }
             }
          }
       });
    }

    isInitialLoad = false;
    callback(notifications);
  }, (error) => {
    if (error.code !== 'permission-denied') {
      console.error('Error subscribing to notifications:', error);
    }
  });
};

export const markAsRead = async (notificationId: string) => {
  try {
    await updateDoc(doc(db, 'notifications', notificationId), {
      read: true
    });
  } catch (error) {
    console.error('Error marking notification as read:', error);
  }
};

export const markAllAsRead = async (userId: string) => {
  try {
    const q = query(
      collection(db, 'notifications'),
      where('recipientId', '==', userId),
      where('read', '==', false)
    );
    const snapshot = await getDocs(q);
    const batch = writeBatch(db);
    snapshot.docs.forEach((doc) => {
      batch.update(doc.ref, { read: true });
    });
    await batch.commit();
  } catch (error) {
    console.error('Error marking all notifications as read:', error);
  }
};

export const deleteNotification = async (notificationId: string) => {
  try {
    await deleteDoc(doc(db, 'notifications', notificationId));
  } catch (error) {
    console.error('Error deleting notification:', error);
  }
};

export const setupPushNotifications = async (userId: string) => {
  if (!messaging) return;
  
  try {
    const permission = await Notification.requestPermission();
    if (permission === 'granted') {
      let registration: ServiceWorkerRegistration | undefined = undefined;
      if ('serviceWorker' in navigator) {
        registration = await navigator.serviceWorker.register('/firebase-messaging-sw.js', { scope: '/' });
        try {
          await registration.update();
        } catch (e) {
          console.warn('SW registration update failed:', e);
        }
        console.log('Service Worker registered and verified active with scope: /');
      }
      
      // Cache-bypass for Firestore updates to avoid quota limits, but SW is guaranteed registered
      const cachedToken = localStorage.getItem(`fcm_token_cache_${userId}`);
      if (cachedToken) {
        console.log('FCM token found in cache, skipping token fetch to prevent quota limits.');
        return;
      }
      
      // Use env-defined VAPID Key if available, otherwise fallback to the default key
      const vapidKey = import.meta.env.VITE_FIREBASE_VAPID_KEY || 'BGcpvXhvVH4uIrCpxRi5D1YykZEvDGKIkP5V2CFTiqp7GZNR166gaaWhfkBnD7foYacjghc8-tUDcD5pMr2Ah78';
      
      const token = await getToken(messaging, { 
        vapidKey: vapidKey,
        serviceWorkerRegistration: registration
      });
      if (token) {
        await updateDoc(doc(db, 'users', userId), { fcmToken: token });
        localStorage.setItem(`fcm_token_cache_${userId}`, token);
        console.log('Push notifications enabled with FCM token');
      }
    }
  } catch (error: any) {
    const isAuthOrVapidMismatch = 
      error?.code === 'messaging/token-subscribe-failed' || 
      error?.message?.includes('authentication credential') || 
      error?.message?.includes('credential') ||
      error?.message?.includes('subscribe-failed') ||
      error?.message?.includes('OAuth 2 access token');

    if (isAuthOrVapidMismatch) {
      console.warn(
        'FCM Subscription Notice: Since a custom Firebase project is active, push notifications require generating a Web Push Certificate (VAPID Key) in the Firebase Console (Project Settings > Cloud Messaging > Web Push certificates). Please configure the environment variable VITE_FIREBASE_VAPID_KEY with this certificate value. In-app and browser notifications will continue to function normally.'
      );
    } else {
      console.error('Error setting up push notifications:', error);
    }
    
    // If we hit a quota exceeded or token subscribe failed, cache a placeholder so we don't spam requests
    if (isAuthOrVapidMismatch || (error?.message && (error.message.includes('Quota exceeded') || error.message.includes('quota') || error.message.includes('subscribe')))) {
      localStorage.setItem(`fcm_token_cache_${userId}`, 'registration_throttled');
    }
  }
};

