import { collection, addDoc, serverTimestamp, query, where, orderBy, onSnapshot, updateDoc, doc, deleteDoc, writeBatch, getDocs, or } from 'firebase/firestore';
import { db } from '../firebase';

export type NotificationType = 
  | 'profile_update' 
  | 'schedule_change' 
  | 'doubt_reply' 
  | 'material_upload' 
  | 'doubt_raised' 
  | 'fee_payment' 
  | 'fee_confirmed' 
  | 'new_student'
  | 'chat_message'
  | 'group_chat_message';

export interface Notification {
  id?: string;
  recipientId?: string;
  targetRole?: 'teacher' | 'student' | 'admin' | 'ALL';
  senderId: string;
  senderName: string;
  title: string;
  message: string;
  type: NotificationType;
  read: boolean;
  createdAt: any;
  timestamp?: any;
  relatedId?: string;
  targetDept?: string;
  targetSem?: string;
  isAnonymous?: boolean;
}

export const sendNotification = async (notification: Omit<Notification, 'id' | 'createdAt' | 'read'>) => {
  await addDoc(collection(db, 'notifications'), {
    ...notification,
    read: false,
    createdAt: serverTimestamp(),
    timestamp: serverTimestamp(),
  });
};

export const subscribeToNotifications = (userId: string, targetRole: string, callback: (notifications: Notification[]) => void, userDept?: string, userSem?: string) => {
  if ('Notification' in window && Notification.permission === 'default') {
    Notification.requestPermission();
  }

  const q = query(
    collection(db, 'notifications'),
    orderBy('createdAt', 'desc')
  );

  let isInitialLoad = true;

  return onSnapshot(q, (snapshot) => {
    let notifications = snapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    } as Notification));
    
    // Client-side filtering to avoid complex composite index error
    notifications = notifications.filter(n => {
      // Don't show notifications generated by the current user
      if (n.senderId === userId) return false;
      
      // Always show direct messages to the user
      if (n.recipientId === userId) return true;
      
      // Filter role base
      if (n.targetRole === targetRole || n.targetRole === 'ALL') {
        // If there are department constraints on the notification and the user has a department to check against
        if (n.targetDept && userDept) {
          if (n.targetDept.toLowerCase() !== userDept.toLowerCase() && n.targetDept !== 'ALL') return false;
        }
        if (n.targetSem && userSem) {
          if (String(n.targetSem) !== String(userSem) && n.targetSem !== 'ALL') return false;
        }
        return true;
      }
      
      return false;
    });
    
    if (!isInitialLoad) {
       snapshot.docChanges().forEach(change => {
          if (change.type === 'added') {
             const newNotif = { id: change.doc.id, ...change.doc.data() } as Notification;
             const isForMe = notifications.some(n => n.id === newNotif.id);
             if (isForMe && !newNotif.read) {
                // Show standard OS-level Notification
                if ('Notification' in window && Notification.permission === 'granted') {
                   new Notification(newNotif.title, {
                      body: newNotif.message,
                      icon: '/vite.svg', // generic icon
                   });
                }
                
                // Play Sound
                try {
                   const AudioContext = window.AudioContext || (window as any).webkitAudioContext;
                   if (AudioContext) {
                     const audioCtx = new AudioContext();
                     const oscillator = audioCtx.createOscillator();
                     const gainNode = audioCtx.createGain();

                     oscillator.type = 'sine';
                     oscillator.frequency.setValueAtTime(800, audioCtx.currentTime);
                     oscillator.frequency.exponentialRampToValueAtTime(1200, audioCtx.currentTime + 0.05);

                     gainNode.gain.setValueAtTime(0, audioCtx.currentTime);
                     gainNode.gain.linearRampToValueAtTime(0.5, audioCtx.currentTime + 0.02);
                     gainNode.gain.linearRampToValueAtTime(0, audioCtx.currentTime + 0.15);

                     oscillator.connect(gainNode);
                     gainNode.connect(audioCtx.destination);

                     oscillator.start(audioCtx.currentTime);
                     oscillator.stop(audioCtx.currentTime + 0.15);
                   }
                } catch(e) {
                   console.log('Audio could not be played', e);
                }
             }
          }
       });
    }

    isInitialLoad = false;
    callback(notifications);
  }, (error) => {
    console.error('Error subscribing to notifications:', error);
  });
};

export const markAsRead = async (notificationId: string) => {
  try {
    await updateDoc(doc(db, 'notifications', notificationId), {
      read: true
    });
  } catch (error) {
    console.error('Error marking notification as read:', error);
  }
};

export const markAllAsRead = async (userId: string) => {
  try {
    const q = query(
      collection(db, 'notifications'),
      where('recipientId', '==', userId),
      where('read', '==', false)
    );
    const snapshot = await getDocs(q);
    const batch = writeBatch(db);
    snapshot.docs.forEach((doc) => {
      batch.update(doc.ref, { read: true });
    });
    await batch.commit();
  } catch (error) {
    console.error('Error marking all notifications as read:', error);
  }
};

export const deleteNotification = async (notificationId: string) => {
  try {
    await deleteDoc(doc(db, 'notifications', notificationId));
  } catch (error) {
    console.error('Error deleting notification:', error);
  }
};
